version: '3'

services:
  web:
    build:
      context: .
      dockerfile: src/backend/Dockerfile
    volumes:
      - ./src/backend:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    expose:
      - 8000
    environment:
      - DEBUG=False
      - SECRET_KEY=django-insecure-4gb_@=dm(gmm6%e$$4)+)tk51hjrc9v7t06qm_jrk0ekk#sa(a

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/deafult.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    depends_on:
      - web

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - web

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=xv8GaClN1wG71CT
      - GF_SECURITY_ADMIN_USER=photosplitter_admin         # Замените на ваше имя пользователя администратора
    depends_on:
      - prometheus

volumes:
  static_volume:
  media_volume:
