version: '3.8'

services:
  web:
    build: ./src/backend
    command: gunicorn facedetect.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./src/backend:/app
    expose:
      - 8000
  nginx:
    image: nginx:1.21.0
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - web
