version: '3'

services:
  web:
    build: ./src/backend
    command: gunicorn facedetect.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./src/backend:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    expose:
      - 8000
    environment:
      - "DJANGO_SECRET_KEY=django-insecure-4gb_@=dm(gmm6%e$$4)+)tk51hjrc9v7t06qm_jrk0ekk#sa(a"
      - "DEBUG=False"
    depends_on:
      - db

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/deafult.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    depends_on:
      - web

volumes:
  static_volume:
  media_volume:
