version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: src/backend/Dockerfile
    command: gunicorn your_project.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./src/backend:/app
      - static_volume:/app/staticfiles
    expose:
      - 8000

volumes:
  static_volume: