# Generated by Django 5.0.1 on 2024-01-26 11:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("support", "0006_usersidentificationphotos_userssavedarchives_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersidentificationphotos",
            name="user_id",
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name="userssavedarchives",
            name="user_id",
            field=models.IntegerField(default=None),
        ),
    ]
