# Generated by Django 5.0.1 on 2024-01-26 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0009_usersidentificationphotos_us'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersidentificationphotos',
            old_name='user_id',
            new_name='id_of_user',
        ),
        migrations.RenameField(
            model_name='userssavedarchives',
            old_name='user_id',
            new_name='id_of_user',
        ),
        migrations.RemoveField(
            model_name='usersidentificationphotos',
            name='us',
        ),
        migrations.AddField(
            model_name='usersidentificationphotos',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
