# Generated by Django 5.0.1 on 2024-01-26 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0010_rename_user_id_usersidentificationphotos_id_of_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersidentificationphotos',
            name='id_of_user',
        ),
        migrations.RemoveField(
            model_name='userssavedarchives',
            name='id_of_user',
        ),
    ]
