# Generated by Django 5.0.1 on 2024-01-26 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("support", "0013_alter_usersidentificationphotos_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usersidentificationphotos",
            name="user",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="support.users",
            ),
        ),
    ]
