# Generated by Django 5.0.1 on 2024-01-29 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0022_remove_eventsheadbands_event_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EventsHeadbands',
            new_name='Headbands',
        ),
        migrations.RenameField(
            model_name='headbands',
            old_name='event',
            new_name='events',
        ),
    ]
