# Generated by Django 5.0.1 on 2024-01-30 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0023_rename_eventsheadbands_headbands_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='headbands',
            old_name='events',
            new_name='user',
        ),
    ]
