# Generated by Django 5.0.1 on 2024-01-30 10:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("support", "0024_rename_events_headbands_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="headbands",
            old_name="user",
            new_name="event",
        ),
    ]
