# Generated by Django 5.0.1 on 2024-01-30 22:14

import support.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("support", "0025_rename_user_headbands_event"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usersidentificationphotos",
            name="identification_photo_archive",
        ),
        migrations.AddField(
            model_name="usersidentificationphotos",
            name="identification_photo_1",
            field=models.ImageField(
                default=None, upload_to=support.models.users_identification_photos_path
            ),
        ),
        migrations.AddField(
            model_name="usersidentificationphotos",
            name="identification_photo_2",
            field=models.ImageField(
                default=None, upload_to=support.models.users_identification_photos_path
            ),
        ),
    ]
