# Generated by Django 5.0.1 on 2024-02-01 20:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0033_pathtoarchiverelease'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(default=None, max_length=254, unique=True, validators=[django.core.validators.EmailValidator(message='Invalid email')]),
        ),
    ]
